version: '3'
services:
  wanted2023-mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: wanted2023
    ports:
      - "3306:3306"
    volumes:
      - ./src/test/resources:/docker-entrypoint-initdb.d

  wanted2023-app:
    image: penekhun/wanted2023-api:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - wanted2023-mysql
    restart: always