name: Validation test for PR

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  checks: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3307
          container port: 3307
          mysql database: 'wanted2023'
          mysql root password: 'testtest1234'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #      - name: Set TEST_DB host/pw from Git env
      #        run: |
      #          echo "TEST_DB_URL=${{ secrets.TEST_DB_URL }}" >> $GITHUB_ENV
      #          echo "TEST_DB_PASSWORD=${{ secrets.TEST_DB_PASSWORD }}" >> $GITHUB_ENV

      - name: Build with Gradle
        run: SPRING_PROFILES_ACTIVE=test ./gradlew clean build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }} # 테스트가 실패하여도 수행
        with:
          files: build/test-results/**/*.xml

