name: Validation test for PR

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  checks: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PENEKHUN_GITHUB_TOKEN }}
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Copy .yml file to source path
        run: ./gradlew copyYml

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }} # 테스트가 실패하여도 수행
        with:
          files: build/test-results/**/*.xml

      - name: Install Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: Docker Image Build And Deploy
        run: |
          docker build --tag ${{ secrets.AZURE_REGISTRY_NAME }}/wanted2023-api .
          docker push ${{ secrets.AZURE_REGISTRY_NAME }}/wanted2023-api

