name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          mysql database: 'wanted2023'
          mysql root password: 'test1234'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: SPRING_PROFILES_ACTIVE=test ./gradlew clean build

      - name: Install Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Export DOCKER_HUB_USERNAME
        run: export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }} >> $GITHUB_ENV

      - name: Docker Image Build
        run: docker build --tag $DOCKER_HUB_USERNAME/wanted2023-api .

      - name: Push to Docker Hub
        run: docker push $DOCKER_HUB_USERNAME/wanted2023-api