name: Validation test for PR

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  checks: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PENEKHUN_GITHUB_TOKEN }}
          submodules: true
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Copy .yml file to source path
        run: ./gradlew copyYml

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }} # 테스트가 실패하여도 수행
        with:
          files: build/test-results/**/*.xml

      - name: Install Docker buildx
        uses: docker/setup-buildx-action@v2.9.1

      - name: Login to Azure Container Registry
        run: docker login -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }} ${{ secrets.AZURE_REGISTRY_SERVER }}

      - name: Docker Compose Build And Deploy
        run: |
          docker-compose build
          docker-compose push
#      - name: Docker Image Build And Deploy
#        run: |
#          docker build . -t ${{ secrets.AZURE_REGISTRY_SERVER }}/wanted2023-api:${{ github.sha }}
#          docker push ${{ secrets.AZURE_REGISTRY_SERVER }}/wanted2023-api:${{ github.sha }}

